import "./globals.css";
import Header from "../components/Header";
import CartProvider from "@/contexts/CartContext";
import SearchProvider from "@/contexts/SearchContext";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SearchProvider>
      <CartProvider>
          <body className="flex flex-col min-h-screen">
            <Header/>
              <main className=" flex-grow">{children}</main>
            <Footer/>
          </body>
      </CartProvider>
      </SearchProvider>
    </html>
  );
}
